Repository stsonline/fudge-promotions-gallery, pull requests merged in 2022-11, with the labels that each got.

#1 feat: support for axios in web component, updated carousel UI
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/assets/css/fudge-promotions-gallery.css
  src/components/FudgePromotionsGallery.vue
  src/main.js
Labels: enhancement

#2 feat: pass uuid & slug to requests
  README.md
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/assets/css/fudge-promotions-gallery.css
  src/components/FudgePromotionsGallery.vue
Labels: Feature, CSS, JS

#3 feat: attribution tracking details & more events
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Feature, JS, Chore: requires testing

#4 fix: parse options as JSON via string
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Bug, Bug: development, JS

#5 feat: re-run setAttributionDetails when setting applicant details
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Feature, JS

#6 feat: add initOnLoad option, debug option, and handle autoplay better
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Feature, JS

#7 feat: pull client IP address from external API, and set hostname
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Feature, JS

#8 fix: resolve fpg:applicant:set event and styling issues
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/assets/css/fudge-promotions-gallery.css
  src/components/FudgePromotionsGallery.vue
Labels: Bug, Bug: production, Feature, CSS, JS

#9 fix: resolve missing promotion image for list display type
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Bug, Bug: production, JS

#10 feat: added features with expandable accordions to list type
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/assets/css/fudge-promotions-gallery.css
  src/components/FudgePromotionsGallery.vue
Labels: Feature, CSS, JS

#11 fix: axe window.open in favour for click hyjack workaround
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Bug, JS

#12 fix: extended redirector to work with Safari
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Bug, Bug: production, JS

#13 fix: invalid variable name
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/components/FudgePromotionsGallery.vue
Labels: Bug, Bug: production, JS

#14 fix: iOS check and render default anchor
  dist/fudge-promotions-gallery.js
  dist/fudge-promotions-gallery.js.map
  dist/fudge-promotions-gallery.min.js
  dist/fudge-promotions-gallery.min.js.map
  package.json
  src/assets/css/fudge-promotions-gallery.css
  src/components/FudgePromotionsGallery.vue
Labels: Bug, CSS, JS
